version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: %POSTGRES_DB%
      POSTGRES_USER: %POSTGRES_USER%
      POSTGRES_PASSWORD: %POSTGRES_PASSWORD%
    ports:
      - %POSTGRES_EXTERNAL_PORT%:%POSTGRES_INTERNAL_PORT%
